In [9]:
import sqlite3
import pandas as pd

df = pd.read_csv('../datasets/Housing.csv')

display(df.head())

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [10]:
print(df.info())

display(df.describe().round(2))

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB
None

             price      area  bedrooms  bathrooms  stories  parking
count       545.00    545.00    545.00     545.00   545.00   545.00
mean    4766729.25   5150.54      2.97       1.29     1.81     0.69
std     1870439.62   2170.14      0.74       0.50     0.87     0.86
min     1750000.00   1650.00      1.00       1.00     1.00     0.00
25%     3430000.00   3600.00      2.00       1.00     1.00     0.00
50%     4340000.00   4600.00      3.00       1.00     2.00     0.00
75%     5740000.00   6360.00      3.00       2.00     2.00     1.00
max    13300000.00  16200.00      6.00       4.00     4.00     3.00

In [ ]:
df['price'] = (df['price'] * 0.039).round(2)

df['area'] = (df['area'] * 0.092903).round(2)
bool_columns = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']

for col in bool_columns:
    # Używamy .map, aby zamienić 'yes'/'no' na 1/0
    df[col] = df[col].map({'yes': 1, 'no': 0})

df['area'] = (df['area'] * 0.092903).round(2)

# 3. Mapowanie statusu umeblowania
furnishing_map = {'unfurnished': 0, 'semi-furnished': 1, 'furnished': 2}
df['furnishingstatus'] = df['furnishingstatus'].map(furnishing_map)

In [12]:
db_path = '../datasets/housing.db'
conn = sqlite3.connect(db_path)

df.to_sql('apartments', conn, if_exists='replace', index=False)

conn = sqlite3.connect('../datasets/housing.db')
df.to_sql('apartments', conn, if_exists='replace', index=False)
conn.close()